name: Buycraft
main: net.buycraft.Plugin
version: 5.5
author: Tebex Technologies Ltd
website: http://buycraft.net
commands:
   ec:
      usage: /<command>
   buycraft:
      usage: /<command> <reload/forcecheck/secret/verify>